### ISSUE TITLE
Spectabis fails to collect art for all games

### ISSUE THREAD

**Issue by RegalPixelKing** [FaithLV/Spectabis#42]
When I choose the "Refetch Boxart" option this error message appears: "Failed to connect to GiantBomb. Is the API key valid?"
I double and triple checked my API key, and yes, it is valid. I also tried using TheGamesDB option to collect boxart and I had the same issue with a slightly different error message, this time it was: "Failed to connect to TheGamesDB."  
The weird thing is that I've never had this problem before, everything used to be fully functional. It was a real plug and play type of situation before now. I have no idea was is causing this or how to fix this.

**Comment by Serbagz** [comment]
This is still happening with the latest version btw...I am also using the giantbomb api. My key also works and is valid. After downloading about 4 coverarts it stalls and I cant download any others for a few hours.

**Comment by CyberFoxHax** [comment]
this is pretty embarrassing since it was me that butchered the old Scrape system. With the 5 redundant systems this surely should NOT happen.

FaithLV published a new version at April 12 and I'm sure that's the version @Serbagz is using. Seeing this was posted 3 days later.
Are you still have the issues? Can you post your configuration files? (maybe delete api keys and stuff first, if any)
Can you check in the settings whether the API priorities is set up correctly. If you configure them manually then you person priorities will *always* take precedence over the computed priorities.

If that is not helping I'm gonna need a debugger on your setup.

**Comment by RegalPixelKing** [comment]
Sorry for not updating for a while, but I thought I should give an update though. I'm no longer having the problem; I kind of gave up and put this on the back burner for a couple of months. Anyways, I got it to work. I got a new hard drive and downloaded a newer version of Spectabis, afterward everything worked out of the box. It's very likely that the problem was on my end and the clean drive made it function. I would not necessarily call this problem "fixed," it was just fixed on my end. Because I remember deleting everything on my computer related to Spectabis and redownloading everything and having the same issues that I described.

**Comment by Serbagz** [comment]
Everything was pretty much default. It has been awhile, Ive slowly over time just downloaded more covers I was missing there are quit a few in my collection that still arent filled, but i'm sure that is probably because they are foreign/translated niche games (dragon quest V ps2, phantasy star sega ages ver etc) my priortities were originally the gamesdb on top taking priority but empty with the giant bomb api 2nd, filled in with my key, followed by the rest in default order all empty.

**Comment by CyberFoxHax** [comment]
The blank field will just use a built-in API key. There is no function to verify if an API key is valid or not. But if you're the default priorities, failing APIs will silently be moved down the list. Se verify:

1. You can actually connect to giantbomb.com.
2. Your API key is valid.
3. Inn the settings GiantBomb is actually the first on the list. If it's not first on the list move it up by the arrows in the settings view. This will also override the computed priorities too.

Can you post the exact ISO names. I can create dummy ISO's and see what happens.


_If the search returned nothing there should be a more transparent and graceful way to handle it._

**Comment by ayoits0913** [comment]
Still an issue, cannot get boxart for any games on the latest version of Windows 10 1909. Made sure it wasn't my firewall or anything blocking the connection. Not sure what to do?

**Comment by CyberFoxHax** [comment]
Can you share the list of filenames?

**Comment by CyberFoxHax** [comment]
I got some info after testing. It appears 3 of our providers is failing. I will have investigate each.

Meanwhile MobyGames and TheGamesDbHtml seems to work fine. Try moving moving them up in the settings.

**Comment by KirbyFan102** [comment]
I'm having the same problem, and I _just_ got an API key.
Also, the program keeps telling me 'a new update is available' but when I click on the message, nothing happens. I know it's not related to this, but is there no way to update from the app itself?

**Comment by KirbyFan102** [comment]
Not to mention it keeps crashing at random...

**Comment by FaithLV** [comment]
Looks like the APIs we were using have been updated.

**Comment by ayoits0913** [comment]
> 
> 
> I got some info after testing. It appears 3 of our providers is failing. I will have investigate each.
> 
> Meanwhile MobyGames and TheGamesDbHtml seems to work fine. Try moving moving them up in the settings.

Neither of those are working for me, they are at the top.

**Comment by ayoits0913** [comment]
Is there a way to add wikipedia as a source? Searching through Google for some covers, since those aren't working for me...the first result is always wikipedia and although the covers are small, they are the cleanest.

**Comment by CyberFoxHax** [comment]
i'll have all API's up and running at the end of this week. Then i'll leave the PR to Faith.

@ayoits0913 about the Wikipedia thing, it could work. but we may not need it since Faith has an ace up his sleeve.

**Comment by Tritix1** [comment]
I am experiencing a similar issue, except the loading animation never stops. I have an API key for GiantBomb but have also rearranged the different API's to see if that would make a difference. I also tried reinstalling but i'm not sure if just deleting the spectabis folder is enough for that.

**Comment by washingleavesandthensome23-434** [comment]
agree ...same issue , giantbomb added to top with api ...cant find shit
